'use strict';
console.log('hello world');
let $h1 = document.querySelector('h1');
console.log('$h1: ', $h1);
console.dir($h1);
let $id = document.querySelector('#explanation');
console.log('$id: ', $id);
console.dir($id);
let $class = document.querySelector('.hint');
console.log('$class: ', $class);
console.dir($class);
let $p = document.querySelectorAll('p');
console.log('$p: ', $p);
let $classList = document.querySelectorAll('.example-link');
console.log('$classList: ', $classList);
