'use strict';
let colors = ['red', 'white', 'blue'];
console['log']('colors[0]: ', colors[0]);
console['log']('colors[1]: ', colors[1]);
console['log']('colors[2]: ', colors[2]);
console['log'](`America is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`);
colors[2] = 'green';
console['log'](`Mexico is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`);
console['log'](colors);
console['log'](`type of colors: ${typeof colors}`);
let students = ['Spongebob', 'Patrick', 'Squidward', 'Eugene'];
let numberOfStudents = students.length;
console.log(`There are ${numberOfStudents} students in the class.`);
let lastIndex = numberOfStudents - 1;
let lastStudent = students[lastIndex];
console.log(`The last student in the array is ${lastStudent}.`);
console.log(students);
console.log(`type of students: ${typeof students}`);
